APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:TjwlJIfee+eKrt4liIP3Ju7AccTki+CbHRbFB0SBhZA=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=confinit_lashowroom
DB_USERNAME=confinit_lashowroom
DB_PASSWORD=confinit_lashowroom

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# MAIL_DRIVER=smtp
# MAIL_HOST=smtp.googlemail.com
# MAIL_PORT=465
# MAIL_USERNAME=meharomer50@gmail.com
# MAIL_PASSWORD=M3har_umar123
# MAIL_FROM_ADDRESS=meharomer50@gmail.com
# MAIL_ENCRYPTION=ssl

MAIL_MAILER=smtp
MAIL_HOST=mail.confinito.com
MAIL_PORT=587
MAIL_USERNAME=no-reply@confinito.com
MAIL_PASSWORD=W&b4jOl+T5vk
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=no-reply@confinito.com
MAIL_FROM_NAME="Lashowroom"

# MAIL_MAILER=smtp
# MAIL_HOST=smtp.googlemail.com
# MAIL_PORT=587
# MAIL_USERNAME=meharomer50@gmail.com
# MAIL_PASSWORD=M3har_umar123
# MAIL_ENCRYPTION=null
# MAIL_FROM_ADDRESS=meharomer50@gmail.com
# MAIL_FROM_NAME="Lashowroom"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
